name: Run tests
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-22.04
    env:
      NXF_VER: 25.10.2
      NXF_ANSI_LOG: false
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Cache singularity/apptainer images
        uses: actions/cache@v5.0.2
        with:
          path: work/singularity
          key: singularity-${{ hashFiles('config/nextflow_config/singularity.config') }}
          restore-keys: singularity-

      - name: Install apptainer 
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6
      
      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: 25.10.2

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
          architecture: x64

      - name: Install test requirements
        run: |
          pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest tests

      - name: Run Black code formatting check
        run: black --check .
